### PR TITLE
Updated information and links

### PR DESCRIPTION
**Pull request by doomrobo**
In particular, the README links were broken. This also clarifies the dual-licensing we all agreed to way back. The MIT license remains at 2014 since it was under the MIT license since then. But the APACHE license wasn't really written anywhere so I made it 2017.

I left the email in `Cargo.toml` the same, since I was unable to find a newer email address.

I would also like to do a little bit of cleanup soon, and make a 1.0 version. I don't think the API is in need of change. Let me know if you have thoughts on this.

### CODE REVIEW

**Comment by purpliminal** [comment]
Thank you so much! I'll change the email as well and merge this.

:100: :+1: to cleanup and 1.0 version. Any specific ideas in mind? Something I (or others) can help with?

**Comment by doomrobo** [comment]
Great. I already went and coded up what I would like to see in my branch [here](https://github.com/doomrobo/rust-iterslide/commits/stabilize). I cleaned up some code and added docs. I also made two big changes, the second of which is technically a breaking change:

1. I implemented `SlideIterator` for `IntoIterator<Item=A> where A: clone`. This is strictly more general than the `Iterator<Item=a> where A: clone` implementation, since every `Iterator` is trivially `IntoIterator`. That means you can (but don't have to) drop all the `into_iter()` calls when using the library.
2. I made the window type a `VecDeque` instead of a `Vec` for efficiency. The `next` function normally pushes to the back of the internal window `Vec`, then pops an element off the front. This pop makes every element shift downwards. This is O(n) behavior on every iteration of the window iterator, where n is the window size. Using a `VecDeque`, we can do the same thing, but with O(1) behavior, since it's a ring buffer. We also don't really lose any functionality because `VecDeque`s are iterable, comparable to a ton of things, and can be turned into `Vec`s pretty easily.

Let me know what you think. Also to check out the docs, you'll have to load it locally, since the docs.rs only points to versions published on crates.io.

**Comment by doomrobo** [comment]
Bump. Any update?

**Comment by purpliminal** [comment]
Oops! This slipped. I'm merging this one first, then I'll check out the cleanup.

**Comment by purpliminal** [comment]
Merged! I've taken the liberty to make a PR out of your above comment, so we can discuss it separately if necessary: #7

Generally, I find all the changes you added desirable, and I feel like the compatibility break isn't a big deal (that's the whole point of 0.x versions :P). Thank you!

**Pull request merged**
